# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    name: Lint & Build & Typecheck

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version-file: package.json

      - uses: oven-sh/setup-bun@v2
        name: Setup bun
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install

      - name: Run Biome
        run: bunx biome ci .

        # NOTE: `Build` requires some environment variables to be set
      - name: Build
        run: |
          NEXT_PUBLIC_PRODUCTION_MODE=true \
          NEXT_PUBLIC_SITE_LOCALE=en \
          bun run build

        # NOTE: `Typecheck` needs to be run after build for content-collections to be generated
      - name: Typecheck
        run: bun run typecheck
