# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    name: Lint & Build & Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        bun-version: [1.1.24]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: ${{ matrix.bun-version }}

      - uses: actions/cache@v4
        name: Setup bun cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun-version }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun-version }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run Biome
        run: bunx biome ci .

        # NOTE: `Build` requires some environment variables to be set
      - name: Build
        run: |
          NEXT_PUBLIC_PRODUCTION_MODE=true \
          NEXT_PUBLIC_SITE_LOCALE=en \
          bun run build

        # NOTE: `Typecheck` needs to be run after build for content-collections to be generated
      - name: Typecheck
        run: bun run typecheck
