# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  checks:
    name: Build & Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        bun-version: [1.1.20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: ${{ matrix.bun-version }}

      - uses: actions/cache@v4
        name: Setup bun cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun-version }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun-version }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck # NOTE: Needs to be run after build for content-collections to be generated
